[package]
name = "mupdf-sys"
version = "0.0.8"
authors = ["messense <messense@icloud.com>"]
edition = "2018"
exclude = [
    "mupdf/resources/fonts/droid/*",
    "mupdf/resources/fonts/han/*",
    "mupdf/resources/fonts/noto/*",
    "mupdf/resources/fonts/sil/*",
    "mupdf/resources/fonts/urw/input/*",
    "mupdf/docs/*",
    "mupdf/generated/*",
    "mupdf/platform/gl/*",
    "mupdf/platform/java/*",
    "mupdf/platform/wasm/*",
    "mupdf/platform/x11/*",
    "mupdf/thirdparty/curl/*",
    "mupdf/thirdparty/freeglut/*",
    "mupdf/thirdparty/lcms2/doc/*",
    "mupdf/thirdparty/lcms2/testbed/*",
    "mupdf/thirdparty/lcms2/plugins/*",
    "mupdf/thirdparty/freetype/docs/*",
    "mupdf/thirdparty/libjpeg/testimg*",
    "mupdf/thirdparty/openjpeg/doc/*",
    "mupdf/thirdparty/harfbuzz/docs/*",
    "mupdf/thirdparty/harfbuzz/test/*",
    "mupdf/thirdparty/mujs/docs/*",
    "mupdf/thirdparty/zlib/doc/*",
    "mupdf/thirdparty/zlib/test/*",
    "mupdf/thirdparty/zlib/contrib/*",
    "mupdf/thirdparty/zlib/examples/*",
    "mupdf/thirdparty/gumbo-parser/test/*",
    "mupdf/thirdparty/gumbo-parser/python/*",
    "mupdf/thirdparty/gumbo-parser/benchmarks/*",
]
description = "Rust FFI binding to MuPDF"
keywords = ["pdf", "mupdf"]
license = "GPL-3.0"
links="mupdf-wrapper"
repository = "https://github.com/messense/mupdf-rs"

[features]
sys-lib = []
js = []
xps = []
svg = []
cbz = []
img = []
html = []
epub = []

[build-dependencies]
bindgen = "0.56"
cc = "1.0.50"
pkg-config = "0.3"

[dependencies]
