[package]
name = "mupdf-sys"
version = "0.1.0"
authors = ["messense <messense@icloud.com>"]
edition = "2018"
links="mupdf-wrapper"

[build-dependencies]
bindgen = "0.52"
cc = "1.0.50"

[dependencies]
